### ISSUE TITLE
Problem in lesson #73

### ISSUE THREAD

**Issue by Mnur86** [CodeYourFuture/orula#139]
**Actual Behaviour** 
On the lesson Edit section when a form is submitted that already exist I got an error message that says " This lesson is already exist or lesson name field is empty" 

When I submit a form with a lesson name but without a date I get an alert message that says "Lesson is successfully updated!"

**Expected Behaviour**
There's an error typo, however  the error message should read "This lesson aready exist or lesson name/date field is empty"

I'm expecting an error message "This lesson aready exist or lesson name/date field is empty!"
when the date section is left empty.

**Comment by islam95** [comment]
not sure why this was in to do when it's done
