### ISSUE TITLE
Users Page : Type Error

### ISSUE THREAD

**Issue by aaronkisac** [CodeYourFuture/orula#168]
at Admin account's users' page, You can't see users without assigned any role.

**Comment by islam95** [comment]
This is not a bug. Any new user is assigned "Student" role. So when new user is registered he is assigned as "Student" automatically. Then Admin can change him as he wish.

**Comment by aaronkisac** [comment]
Ok I couldnt  sing up so I couldnt see that

**Comment by islam95** [comment]
No worries
