### ISSUE TITLE
admin :type error

### ISSUE THREAD

**Issue by aaronkisac** [CodeYourFuture/orula#171]
lesson/lesson_Id
admin can not see second student information on this page

**Comment by islam95** [comment]
Could you clarify what is wrong in more details? Which second student? Why admin needs to see it? We didn't discuss that admin will access `lesson/:lessonId` page. I don't remember such task existed in our MVP. If so, this is not a bug, it's a new issue/task that can be done in the future.

**Comment by aaronkisac** [comment]
I don't know this task what is the goal but admin can see all of student's information in one topic. Right? But I assigned 2 students in same class and I filled first lesson's rates but admin could just see one student information. I thought it was bug.

**Comment by islam95** [comment]
Admin don't need to see this page. Or we just didn't discuss that.

**Comment by islam95** [comment]
But we should do something with this. @NateWr can tell us what we need to do with it.

**Comment by aaronkisac** [comment]
Admin is also  mentor. I thought  If admin can't see that also mentor can't see that

**Comment by islam95** [comment]
No, if one of the user's role is "Mentor", he should be able to see that.

**Comment by NateWr** [comment]
Can someone describe the desired feature as a user story?

**As a**
**I want to**
**So that I can**

**Comment by aaronkisac** [comment]
yes I couldnt that
