### ISSUE TITLE
Use bootstrap theme for Back-end

### ISSUE THREAD

**Issue by islam95** [CodeYourFuture/orula#41]
Use this theme for the back-end (Node, Handlebars)
https://startbootstrap.com/template-overviews/sb-admin-2/

   
                                      TC03 : TO TEST IF SERVER IS WORKING
PRECONDITIONS/GENERAL REQUIREMENTS:
1 . Start the server ,
2 . Navigate  to the URL , e.g . localhost : 4000
Test Steps :
1 . make a server request in the browser , e.g 
http://localhost: 4000/orula/server/classes
Expected Results:
The browser should display list of classes.

**Comment by NateWr** [comment]
This is a duplicate of #39.

**Comment by islam95** [comment]
I think we need to close this issue as we no longer need backend bootstrap.
