### ISSUE TITLE
Admin can create organisations

### ISSUE THREAD

**Issue by NateWr** [CodeYourFuture/orula#62]
**As an** admin
**I want to** create organisations
**so that I can** assign courses to organisations.

## Technical Requirements
- A database table named `organisations`, which matches the specification in our database outline.
- An API endpoint, `/api/organisations`, which accepts a `POST` request. It should receive an organisation's `name` and create a new entry in the database. (Server)
- An admin dashboard, `/admin`, which includes an Add Organisation button. (Client)
- A page, `/admin/organisations/add`, which displays a form for adding an organisation. The form should submit to the `/api/organisations` endpoint on the server.

## Acceptance Criteria
- [x] I can access the admin dashboard at `/admin`.
- [x] I can click on the Add Organisation button the admin dashboard to go to the form for adding an organisation.
- [x] I can see the form to enter the name of a new organisation.
- [x] When I submit the form, I see a confirmation message that the organisation has been added to the database.
- [x] When I submit the form without a name, I see an error message that says I must provide a name.
- [x] When I submit the form with a name that already exists in the database, I see an error that says the organisation already exists.

**Comment by NateWr** [comment]
@okolochuks or @Mnur86: now that `review wanted` label has been added, can one of you test this issue and see if all of the acceptance criteria are passed? If so, post here to let us know so that we can close the issue and move it to Done.

**Comment by alastair87** [comment]
[Test Case 01.docx](https://github.com/CodeYourFuture/orula/files/2315411/Test.Case.01.docx)
