### ISSUE TITLE
Admin can create courses

### ISSUE THREAD

**Issue by NateWr** [CodeYourFuture/orula#66]
**As an** admin
**I want to** create a course
**so that I can** manage the courses that are available.

## Technical Requirements
- A database table named `courses`, which matches the specification in our database outline.
- An API endpoint, `/api/courses`, which accepts a `POST` request. It should receive a course's `name`, `location` and `organisation_id`, and create a new entry in the database. (Server)
- On the admin dashboard, `/admin`, there should be an Add Course button. (Client)
- A page, `/admin/courses/add`, which displays a form for adding a course. The form should submit to the `/api/courses` endpoint on the server.

## Acceptance Criteria
- [x] I can click on the Add Course button in the admin dashboard to go to the form for adding a course.
- [x] I can see the form to enter the name, location and organisation of a new course.
- [x] When I submit the form, I see a confirmation message that the course has been added to the database.
- [x] When I submit the form without selecting an organisation for the course, I see an error message that says I must select an organisation.
- [x] When I submit the form without a name, I see an error message that says I must provide a name.
- [x] When I submit the form with a name that already exists in the database, I see an error that says the course already exists.

**Comment by NateWr** [comment]
Wireframe for the add course form:

<img width="753" alt="screen shot 2018-08-19 at 16 13 56" src="https://user-images.githubusercontent.com/2639155/44310252-0c02d180-a3cb-11e8-9fdc-1db71c4a5d1f.png">

**Comment by islam95** [comment]
This issue is complete. Please can you review it and test
