### ISSUE TITLE
Admin can edit a topic

### ISSUE THREAD

**Issue by NateWr** [CodeYourFuture/orula#78]
**As an** admin
**I want to** edit a topic
**so that I can** change the information when a topic changes.

## Technical Requirements
- An API endpoint, `/api/topics/:topicId`, which accepts a `PUT` request. It should receive a `name` and `lessonId`, change the details in the database, and return the new topic details. (Server)
- A page, `/admin/topics/edit/:topicId`, which displays a form to change the topic details. (Client)

## Acceptance Criteria
- [x] From the list of topics assigned to a lesson, I can see an "Edit" button next to the name of each topic.
- [x] When I click the "Edit" button for a topic, I see a form to change all the details of the topic.
- [x] When I submit the form, I see a message saying that the details have been changed.
- [x] From the edit form, I can click a link to go back to the list of topics assigned to the same lesson as the current topic.
- [x] When I submit the form without a name or lesson, I see an error message saying that all fields are required.
- [x] When I submit the form with a name that is already assigned to another topic for the same lesson, I see an error message saying that the topic already exists.
- [x] After I submit the form, the input and select fields should still be set with the values so the user can continue to edit it.

**Comment by Mnur86** [comment]
**From the Acceptance Criteria**
When I submit a form, I see a message saying that the details have been changed.

**Actual Behaviour** 
When I submit a form, I see a message saying "Lesson is successfully updated!"

**Expected Behaviour**
When I submit a form, I see a message saying that "the details have been changed."
