### ISSUE TITLE
Users can edit their profile

### ISSUE THREAD

**Issue by NateWr** [CodeYourFuture/orula#83]
**As a** user
**I want to** edit my profile
**so that I can** change my details.

## Technical Requirements
- An API endpoint, `/users/:userId`, which accepts a `PUT` request with the `name`, `email` and `password`, and updates the details.
- A page, `/profile/edit`, where a user can edit their own details.

## Acceptance Criteria
- [x] As a logged in user, I can go to my profile and click on an "Edit" link.
- [x] After clicking the "edit" link, I can fill out a form with my name, email address and password.
- [x] When I submit the form, my details are changed.
- [x] When I submit the form without a name, email address or password, I receive an error message.

**Comment by shawki2** [comment]
Nate told me, I should just finish the API endpoint without the client because Austine will do it.

**Comment by NateWr** [comment]
@shawki2 Has your contribution to this issue been completed and merged in? If so I'll change the assignment.

**Comment by llh1** [comment]
To keep this task simple for now, here is the decision we took about updating the password:

- [x] If the user doesn't fill the password field, then the form can be submitted and the password will not be updated .
- [x] If the user fill the password field, then the password will be updated.
- [x] A message should be displayed near the Password label to inform the user that the password field should be filled only if the password needs to be updated.

**Comment by llh1** [comment]
Additional criteria for editing the email:

- [x] If the user edits their email and choose an email which already belongs to an other existing user, an error should be displayed.

**Comment by shawki2** [comment]
I have just finished all these extensions and I will push the code soon. Thanks, Loic @llh1 and Nate @NateWr.
