### ISSUE TITLE
Admin can assign students to courses

### ISSUE THREAD

**Issue by NateWr** [CodeYourFuture/orula#84]
**As an** admin
**I want to** assign a student to a course
**so that they can** access lessons and topics.

## Technical Requirements
- Add a new POST API to assign a student to a course `/enrol` which take the following parameters in the body `{ course_id: 1, user_id: 2 }` (SERVER)
- Add a new GET API to get the list of student names assigned to a course: `/courses/:id/students`
- Add a new admin page `/admin/courses/:courseId` following the design below. It should display the name of the course, the number of assigned students, all the name of the students enrolled in this course, and a form to add a new student (CLIENT)
- Only user with the student role should be displayed in the select menu to be assigned to the course.

## Acceptance Criteria
- [x] As an admin, I can see all students assigned to a course when I go to `/admin/courses/:courseId`.
- [x] I can see the number of students to the course when I go to `/admin/courses/:courseId`.
- [x] When I go to `/admin/courses/:courseId`, I can see a select menu with the name of the students, then I can select one student and assign it to this course.
- [x] When I assign a student to the course, the number of students is updated on the page and the new student name appears in the list of students enrolled for this course.
- [x] As an admin, when I go to `/admin/courses`, I can click on the course name and go to the new `/admin/courses/:courseId` page.

<img width="751" alt="screen shot 2018-09-23 at 11 22 52" src="https://user-images.githubusercontent.com/2639155/45926953-157bde00-bf23-11e8-9810-6c30086f3470.png">

**Comment by shawki2** [comment]
@NateWr and @llh1. Could you please add the technical requirements and acceptance criteria, please?

**Comment by NateWr** [comment]
@shawki2 Sorry, I must have forgotten this one. I've added some acceptance criteria that should hopefully make the details more clear.
