### ISSUE TITLE
Admin can assign user to a role

### ISSUE THREAD

**Issue by NateWr** [CodeYourFuture/orula#91]
**As an** admin
**I want to** assign a user to a role
**so that they can** access the right parts of the app.

## Technical Requirements
- A new database table, `user_roles`, according to the specifications. (Server)
- A page which lists all users with an edit button. (Client)
- A page with a form to assign a user a role. (Client)

## Acceptance Criteria
- [x] I can click a link to view all users and their roles from the dashboard.
- [x] I can see an "Assign Roles" button beside each user in the list.-
- [x] When I click on the "Assign Roles" button, I go to a page with a form where I can assign one or many roles to a user.
- [x] When I submit the form, the user's roles change.

**Comment by islam95** [comment]
@NateWr May I ask what are the specifications for this table -> `A new database table, user_roles, according to the specifications. (Server)`?

**Comment by NateWr** [comment]
The db specification diagram is in the Slack channel. To find it, you go to the project channel, and then click on the little "pin" icon under the channel title. That will show you the pinned posts, and one of them is the db schema Austine drew up.

**Comment by islam95** [comment]
Thanks, should I name it `user_roles` or `users_roles`?

**Comment by NateWr** [comment]
Looks like `users_roles`.

**Comment by islam95** [comment]
In the Assign Role page, should the form allow to edit the user details, like name, email etc? Or is it just to set roles for a particular user?

**Comment by NateWr** [comment]
Up to you.
